import math
import colour
from enum import Enum
import pyautogui


#user will need permission to access X server
# can be added with: xhost +SI:localuser:$(whoami)

#gets color under cursor with RGB, gets closest color in palettes provided
# in this case, checks against pico8 color palette and another generated by mixing pico8 colors to approximate the effect that dithering them would have
# there are other methods of finding color distance provided as functions

class method(Enum):
    PYTHAGOREAN = 1
    REDMEAN = 2
    DELTA_E = 3

def closest_color(input_color, method = method.DELTA_E):
    return min(pico_base_colors, key=lambda x: color_distance(x, input_color, method))

def closest_dither(input_color, method = method.DELTA_E):
    return min(pico_dithered_colors, key=lambda x: color_distance(x, input_color, method))

def color_mixer(color1, color2):
    result = (math.ceil((color1[0]+color2[0])/2),
              math.ceil((color1[1]+color2[1])/2),
              math.ceil((color1[2]+color2[2])/2))
    return result

def color_distance(A, B, method = method.DELTA_E):
    match method:
        case method.PYTHAGOREAN:
            return pythagorean_distance(A, B)
        case method.REDMEAN:
            return redmean_distance(A,B)
        case method.DELTA_E:
            return delta_e_distance(A, B)

def pythagorean_distance(input_color, target_color):
    return pow((input_color[0] - target_color[0]),2)+pow((input_color[1] - target_color[1]),2)+pow((input_color[2] - target_color[2]),2)

def redmean_distance(input_color, target_color):
    r_bar = (1/2) * (input_color[0] + target_color[0])
    r_delta = input_color[0] - target_color[0]
    g_delta = input_color[1] - target_color[1]
    b_delta = input_color[2] - target_color[2]
    return math.sqrt((2 + r_bar / 256) * pow(r_delta, 2) + 4 * pow(g_delta, 2) + (2 + (255 - r_bar) / 256) * pow(b_delta, 2))

def delta_e_distance(A, B):
    return colour.delta_E(colour.RGB_to_ICtCp(A), colour.RGB_to_ICtCp(B))

#color palette of the pico8
pico_base_colors = [(0,0,0), (29,43,83), (126,37,83), (95,87,79), 
                    (171,82,54), (255,0,77), (0, 228, 54), (0,135,81),
                    (255,163,0), (255,236,39), (131,118,156), (255, 119, 168),
                    (41,173,255), (255,204,170), (194, 195,199), (255, 241,232)]

#each combination of color approximations that can be made by dithering pico8 colors
pico_dithered_colors = [
    (0, 0, 0), (15, 22, 42), (63, 19, 42), (48, 44, 40), (86, 41, 27), (128, 0, 39), (0, 114, 27), (0, 68, 41),
    (128, 82, 0), (128, 118, 20), (66, 59, 78), (128, 60, 84), (21, 87, 128), (128, 102, 85), (97, 98, 100), (128, 121, 116),

    (15, 22, 42), (29, 43, 83), (78, 40, 83), (62, 65, 81), (100, 63, 69), (142, 22, 80), (15, 136, 69), (15, 89, 82),
    (142, 103, 42), (142, 140, 61), (80, 81, 120), (142, 81, 126), (35, 108, 169), (142, 124, 127), (112, 119, 141), (142, 142, 158),

    (63, 19, 42), (78, 40, 83), (126, 37, 83), (111, 62, 81), (149, 60, 69), (191, 19, 80), (63, 133, 69), (63, 86, 82),
    (191, 100, 42), (191, 137, 61), (129, 78, 120), (191, 78, 126), (84, 105, 169), (191, 121, 127), (160, 116, 141), (191, 139, 158),

    (48, 44, 40), (62, 65, 81), (111, 62, 81), (95, 87, 79), (133, 85, 67), (175, 44, 78), (48, 158, 67), (48, 111, 80),
    (175, 125, 40), (175, 162, 59), (113, 103, 118), (175, 103, 124), (68, 130, 167), (175, 146, 125), (145, 141, 139), (175, 164, 156),

    (86, 41, 27), (100, 63, 69), (149, 60, 69), (133, 85, 67), (171, 82, 54), (213, 41, 66), (86, 155, 54), (86, 109, 68),
    (213, 123, 27), (213, 159, 47), (151, 100, 105), (213, 101, 111), (106, 128, 155), (213, 143, 112), (183, 139, 127), (213, 162, 143),

    (128, 0, 39), (142, 22, 80), (191, 19, 80), (175, 44, 78), (213, 41, 66), (255, 0, 77), (128, 114, 66), (128, 68, 79),
    (255, 82, 39), (255, 118, 58), (193, 59, 117), (255, 60, 123), (148, 87, 166), (255, 102, 124), (225, 98, 138), (255, 121, 155),

    (0, 114, 27), (15, 136, 69), (63, 133, 69), (48, 158, 67), (86, 155, 54), (128, 114, 66), (0, 228, 54), (0, 182, 68),
    (128, 196, 27), (128, 232, 47), (66, 173, 105), (128, 174, 111), (21, 201, 155), (128, 216, 112), (97, 212, 127), (128, 235, 143),

    (0, 68, 41), (15, 89, 82), (63, 86, 82), (48, 111, 80), (86, 109, 68), (128, 68, 79), (0, 182, 68), (0, 135, 81),
    (128, 149, 41), (128, 186, 60), (66, 127, 119), (128, 127, 125), (21, 154, 168), (128, 170, 126), (97, 165, 140), (128, 188, 157),

    (128, 82, 0), (142, 103, 42), (191, 100, 42), (175, 125, 40), (213, 123, 27), (255, 82, 39), (128, 196, 27), (128, 149, 41),
    (255, 163, 0), (255, 200, 20), (193, 141, 78), (255, 141, 84), (148, 168, 128), (255, 184, 85), (225, 179, 100), (255, 202, 116),

    (128, 118, 20), (142, 140, 61), (191, 137, 61), (175, 162, 59), (213, 159, 47), (255, 118, 58), (128, 232, 47), (128, 186, 60),
    (255, 200, 20), (255, 236, 39), (193, 177, 98), (255, 178, 104), (148, 205, 147), (255, 220, 105), (225, 216, 119), (255, 239, 136),

    (66, 59, 78), (80, 81, 120), (129, 78, 120), (113, 103, 118), (151, 100, 105), (193, 59, 117), (66, 173, 105), (66, 127, 119),
    (193, 141, 78), (193, 177, 98), (131, 118, 156), (193, 119, 162), (86, 146, 206), (193, 161, 163), (163, 157, 178), (193, 180, 194),

    (128, 60, 84), (142, 81, 126), (191, 78, 126), (175, 103, 124), (213, 101, 111), (255, 60, 123), (128, 174, 111), (128, 127, 125),
    (255, 141, 84), (255, 178, 104), (193, 119, 162), (255, 119, 168), (148, 146, 212), (255, 162, 169), (225, 157, 184), (255, 180, 200),

    (21, 87, 128), (35, 108, 169), (84, 105, 169), (68, 130, 167), (106, 128, 155), (148, 87, 166), (21, 201, 155), (21, 154, 168),
    (148, 168, 128), (148, 205, 147), (86, 146, 206), (148, 146, 212), (41, 173, 255), (148, 189, 213), (118, 184, 227), (148, 207, 244),

    (128, 102, 85), (142, 124, 127), (191, 121, 127), (175, 146, 125), (213, 143, 112), (255, 102, 124), (128, 216, 112), (128, 170, 126),
    (255, 184, 85), (255, 220, 105), (193, 161, 163), (255, 162, 169), (148, 189, 213), (255, 204, 170), (225, 200, 185), (255, 223, 201),

    (97, 98, 100), (112, 119, 141), (160, 116, 141), (145, 141, 139), (183, 139, 127), (225, 98, 138), (97, 212, 127), (97, 165, 140),
    (225, 179, 100), (225, 216, 119), (163, 157, 178), (225, 157, 184), (118, 184, 227), (225, 200, 185), (194, 195, 199), (225, 218, 216),

    (128, 121, 116), (142, 142, 158), (191, 139, 158), (175, 164, 156), (213, 162, 143), (255, 121, 155), (128, 235, 143), (128, 188, 157),
    (255, 202, 116), (255, 239, 136), (193, 180, 194), (255, 180, 200), (148, 207, 244), (255, 223, 201), (225, 218, 216), (255, 241, 232)
]

pos = pyautogui.position()
img = pyautogui.screenshot(region=(pos.x, pos.y, pos.x, pos.y))
rgb_img = img.convert('RGB')
rgb = rgb_img.getpixel((0,0))
print(f'RGB value of pixel: {rgb}')
print("Pico8 ICtCP closest: ", closest_color(rgb, method.DELTA_E))
dither_closest_result = closest_dither(rgb, method.DELTA_E)
print("Pico8 dithered ICtCP closest: ", dither_closest_result)

#get index of closest dithered color combination, then get indices of the source colors from the strict pico8 palette
index = pico_dithered_colors.index(dither_closest_result)
a = index // 16
b = index % 16
print(f'dither composed of source colors: {a},{b}')
